### ISSUE TITLE
Add vars for package names and config files

### ISSUE THREAD

**Issue by ppetrou** [ppetrou/infra_server_pxe_setup#1]
Considering introducing vars for the package names and the configuration files.
At the moment they are hard-coded in the tasks/main.yml but they are not often referenced.

The same applies for the service names and firewall rules.

e.g.

vars/main.yml

```
dnsmasq_package: dnsmasq
dnsmasq_config: /etc/dnsmasq.conf
```

tasks/main.yml

```
# Install and configure DNSMASQ Server
- name: Install and configure DNSMASQ Server
  package:
    name: "{{ dnsmasq_package }}"
    state: present

# Generate DNSMASQ Config
- name: Generate DNSMASQ Config
  template:
    src: templates/dnsmasq.conf.j2
    dest: "{{ dnsmasq_config }}"
```
